version: 2
updates:
  # Enable version updates for Python
  - package-ecosystem: "pip"
    # Look for Python dependencies files in the `root` directory
    directory: "/"
    # Check for updates every day (weekdays)
    schedule:
      interval: "daily"
    # Allow up to 10 open pull requests
    open-pull-requests-limit: 10